# Generated by Django 5.0.7 on 2024-07-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='username',
            new_name='un',
        ),
    ]
